// Auto-generated from traduction.txt - DO NOT EDIT MANUALLY
export const eventSchedules: Record<string, string> = {
  '1-y Loan Prime Rate': '20e – 03h15',
  '10-y Bond Auction': 'Variable',
  '30-y Bond Auction': 'Variable',
  '5-y Loan Prime Rate': '20e – 03h15',
  'ADP Non-Farm Employment Change': 'Mercredi (2 jours avant NFP) – 14h15',
  'API Weekly Statistical Bulletin': 'Mardi – 22h30',
  'Advance GDP Price Index q/q': 'Trimestriel – 14h30',
  'Advance GDP q/q': 'Trimestriel – 14h30',
  'Average Hourly Earnings m/m': '1er vendredi – 14h30',
  'BSI Manufacturing Index': 'Variable',
  'Bank Stress Test Results': 'Variable (Fed CCAR)',
  'Beige Book': 'Mercredi (2 semaines avant FOMC) – 20h00',
  'Building Permits': '3e semaine – 14h30',
  'Building Permits m/m': '3e semaine – 14h30',
  'Business Inventories m/m': '2e semaine – 16h00',
  'CB Consumer Confidence': 'Dernier mardi – 16h00',
  'CB Leading Index m/m': '3e semaine – 16h00',
  'CPI Flash Estimate y/y': 'Variable – 14h30',
  'CPI m/m': '2e semaine – 14h30',
  'CPI q/q': 'Trimestriel (avec PIB) – 14h30',
  'CPI y/y': '2e semaine – 14h30',
  'Capacity Utilization Rate': '3e semaine – 15h15',
  'Challenger Job Cuts y/y': '1er jeudi – 13h30',
  'Chicago PMI': 'Dernier jour ouvré – 15h45',
  'Cleveland Fed Inflation Expectations': '10e – 16h00',
  'Congressional Elections': 'Nov. (années paires) – non planifié',
  'Construction PMI': 'Variable',
  'Construction Spending m/m': '1er jour ouvré – 16h00',
  'Consumer Confidence': 'Dernier mardi – 16h00',
  'Core CPI Flash Estimate y/y': 'Variable – 14h30',
  'Core CPI m/m': '2e semaine – 14h30',
  'Core CPI y/y': '2e semaine – 14h30',
  'Core Durable Goods Orders m/m': '4e semaine – 14h30',
  'Core PCE Price Index m/m': '4e semaine – 14h30',
  'Core PPI m/m': '2e semaine – 14h30',
  'Core Retail Sales m/m': '2e semaine – 14h30',
  'Core Retail Sales q/q': '2e semaine – 14h30',
  'Crude Oil Inventories': 'Mercredi – 16h30',
  'Durable Goods Orders m/m': '4e semaine – 14h30',
  'Empire State Manufacturing Index': '15e – 14h30',
  'Employment Change q/q': 'Trimestriel (avec PIB) – 14h30',
  'Employment Cost Index q/q': 'Dernier mardi du mois – 14h30',
  'Existing Home Sales': '3e semaine – 16h00',
  'FOMC Economic Projections': 'FOMC trimestriel – 20h00',
  'FOMC Financial Stability Report': 'Mai & Novembre – 17h00',
  'FOMC Meeting Minutes': '3 semaines après – 20h00',
  'FOMC Member Barkin Speaks': 'Variable',
  'FOMC Member Barr Speaks': 'Variable',
  'FOMC Member Bostic Speaks': 'Variable',
  'FOMC Member Bowman Speaks': 'Variable',
  'FOMC Member Collins Speaks': 'Variable',
  'FOMC Member Cook Speaks': 'Variable',
  'FOMC Member Daly Speaks': 'Variable',
  'FOMC Member Goolsbee Speaks': 'Variable',
  'FOMC Member Hammack Speaks': 'Variable',
  'FOMC Member Harker Speaks': 'Variable',
  'FOMC Member Jefferson Speaks': 'Variable',
  'FOMC Member Kashkari Speaks': 'Variable',
  'FOMC Member Kugler Speaks': 'Variable',
  'FOMC Member Logan Speaks': 'Variable',
  'FOMC Member Mester Speaks': 'Variable',
  'FOMC Member Miran Speaks': 'Variable',
  'FOMC Member Musalem Speaks': 'Variable',
  'FOMC Member Paulson Speaks': 'Variable',
  'FOMC Member Schmid Speaks': 'Variable',
  'FOMC Member Waller Speaks': 'Variable',
  'FOMC Member Williams Speaks': 'Variable',
  'FOMC Press Conference': 'FOMC – 20h30',
  'FOMC Statement': 'FOMC – 20h00',
  'Factory Orders m/m': '1ère semaine – 16h00',
  'Fed Chair Powell Speaks': 'Variable',
  'Fed Chair Powell Testifies': 'Variable',
  'Fed Monetary Policy Report': 'Février & Juillet – 17h00',
  'Federal Budget Balance': '15e – 20h00',
  'Federal Election': 'Non applicable',
  'Federal Funds Rate': 'FOMC – 20h00',
  'Final CPI y/y': '2e semaine – 14h30',
  'Final Core CPI y/y': '2e semaine – 14h30',
  'Final Employment Change q/q': 'Trimestriel (finale) – 14h30',
  'Final GDP Price Index q/q': 'Trimestriel (finale) – 14h30',
  'Final GDP Price Index y/y': 'Trimestriel (finale) – 14h30',
  'Final GDP q/q': 'Trimestriel (finale) – 14h30',
  'Final Manufacturing PMI': '3e jour ouvré – 15h45',
  'Final Services PMI': '5e jour ouvré – 15h45',
  'Final Wholesale Inventories m/m': '2e semaine – 16h00',
  'Flash Employment Change q/q': 'Trimestriel (flash) – 14h30',
  'Flash GDP q/q': 'Trimestriel (flash) – 14h30',
  'Flash Manufacturing PMI': '23e du mois – 15h45',
  'Flash Services PMI': '23e – 15h45',
  'Foreign Securities Purchases': '15e – 22h00',
  'GDP q/q': 'Trimestriel – 14h30',
  'Goods Trade Balance': '4e semaine – 14h30',
  'HPI m/m': '4e mardi – 15h00',
  'HPI y/y': '4e mardi – 15h00',
  'Household Spending m/m': '4e semaine – 14h30',
  'Household Spending y/y': '4e semaine – 14h30',
  'Housing Starts': '3e semaine – 14h30',
  'Housing Starts y/y': '3e semaine – 14h30',
  'ISM Manufacturing PMI': '1er jour ouvré – 16h00',
  'ISM Manufacturing Prices': '1er jour ouvré – 16h00',
  'ISM Services PMI': '3e jour ouvré – 16h00',
  'Import Prices m/m': '2e semaine – 14h30',
  'Import Prices q/q': '2e semaine – 14h30',
  'Industrial Production m/m': '3e semaine – 15h15',
  'Industrial Production y/y': '3e semaine – 15h15',
  'JOLTS Job Openings': 'Mardi (1er semaine) – 16h00',
  'Jackson Hole Symposium': 'Août – variable',
  'Labor Cost Index q/q': 'Trimestriel – 14h30',
  'Labor Productivity q/q': '1ère semaine – 14h30',
  'Leading Indicators': '3e semaine – 16h00',
  'MI Inflation Expectations': '2e/4e vendredi – 16h00',
  'MI Inflation Gauge m/m': '2e/4e vendredi – 16h00',
  'MI Leading Index m/m': '2e/4e vendredi – 16h00',
  'Manufacturing PMI': '1er jour ouvré – 15h45',
  'Median CPI y/y': '2e semaine – 14h30',
  'Monetary Base y/y': '15e – 22h00',
  'Mortgage Approvals': 'Variable – 15h00',
  'Mortgage Delinquencies': 'Variable – 15h00',
  'NAHB Housing Market Index': '3e semaine – 16h00',
  'NFIB Small Business Index': '2e mardi – 12h00',
  'Natural Gas Storage': 'Jeudi – 16h30',
  'New Home Prices m/m': '4e semaine – 16h00',
  'New Home Sales': '4e semaine – 16h00',
  'Non-Farm Employment Change': '1er vendredi du mois – 14h30',
  'Non-Manufacturing PMI': '3e jour ouvré – 15h45',
  'PPI Input m/m': '2e semaine – 14h30',
  'PPI Input q/q': '2e semaine – 14h30',
  'PPI Output m/m': '2e semaine – 14h30',
  'PPI Output q/q': '2e semaine – 14h30',
  'PPI m/m': '2e semaine – 14h30',
  'PPI q/q': '2e semaine – 14h30',
  'PPI y/y': '2e semaine – 14h30',
  'Pending Home Sales m/m': '4e semaine – 16h00',
  'Personal Income m/m': '4e semaine – 14h30',
  'Personal Spending m/m': '4e semaine – 14h30',
  'Philly Fed Manufacturing Index': '3e jeudi – 14h30',
  'Prelim Business Investment q/q': 'Trimestriel – 14h30',
  'Prelim Flash GDP q/q': 'Trimestriel – 14h30',
  'Prelim GDP Price Index q/q': 'Trimestriel – 14h30',
  'Prelim GDP Price Index y/y': 'Trimestriel – 14h30',
  'Prelim GDP q/q': 'Trimestriel – 14h30',
  'Prelim Industrial Production m/m': '3e semaine – 15h15',
  'Prelim Nonfarm Productivity q/q': '1ère semaine – 14h30',
  'Prelim Unit Labor Costs q/q': '1ère semaine – 14h30',
  'Prelim UoM Consumer Sentiment': '2e vendredi – 16h00',
  'Prelim UoM Inflation Expectations': '2e vendredi – 16h00',
  'Prelim Wholesale Inventories m/m': '2e semaine – 16h00',
  'President Biden Speaks': 'Variable',
  'President Trump Speaks': 'Variable',
  'Presidential Election': 'Nov. 2028 – non planifié',
  'RCM/TIPP Economic Optimism': '2e semaine – 16h00',
  'Retail Sales m/m': '2e semaine – 14h30',
  'Retail Sales q/q': '2e semaine – 14h30',
  'Retail Sales y/y': '2e semaine – 14h30',
  'Revised Business Investment q/q': 'Trimestriel – 14h30',
  'Revised GDP q/q': 'Trimestriel – 14h30',
  'Revised Industrial Production m/m': '3e semaine – 15h15',
  'Revised Nonfarm Productivity q/q': '1ère semaine – 14h30',
  'Revised Unit Labor Costs q/q': '1ère semaine – 14h30',
  'Revised UoM Consumer Sentiment': '4e vendredi – 16h00',
  'Revised UoM Inflation Expectations': '4e vendredi – 16h00',
  'Richmond Manufacturing Index': '4e mardi – 16h00',
  'TIC Long-Term Purchases': '15e – 22h00',
  'Trade Balance': '1ère semaine – 14h30',
  'Treasury Currency Report': 'Avril & Octobre – 22h00',
  'Treasury Sec Yellen Speaks': 'Variable',
  'Trimmed CPI y/y': '2e semaine – 14h30',
  'Trimmed Mean CPI q/q': '2e semaine – 14h30',
  'USD-Denominated Trade Balance': '1ère semaine – 14h30',
  'Unemployment Claims': 'Jeudi – 14h30',
  'Unemployment Rate': '1er vendredi – 14h30',
  'Wards Total Vehicle Sales': 'Variable',
  'Wholesale Sales m/m': '2e semaine – 16h00',
  'ECB Economic Bulletin': 'Variable – 10h00',
  'ECB Financial Stability Review': 'Mai & Nov. – 10h00',
  'ECB Monetary Policy Meeting Accounts': '4 semaines après – 13h30',
  'ECB President Lagarde Speaks': 'Variable',
  'ECB Press Conference': 'BCE – 14h45',
  'ECOFIN Meetings': 'Mensuel – variable',
  'EU Economic Forecasts': 'Février, Mai, Nov. – 11h00',
  'Euro Summit': 'Variable',
  'Eurogroup Meetings': 'Mensuel – variable',
  'European Parliamentary Elections': 'Juin (tous les 5 ans)',
  'Main Refinancing Rate': 'BCE – 13h45',
  'Monetary Policy Meeting Minutes': '4 semaines après – 13h30',
  'Monetary Policy Report Hearings': 'Variable',
  'Monetary Policy Statement': 'BCE – 13h45',
  'Monetary Policy Summary': 'BCE – 13h45',
  'Summary of Monetary Policy Discussions': '4 semaines après – 13h30',
  'WEF Annual Meetings': 'Janvier – variable',
  'Annual Budget Release': 'Variable (Bundeshaushalt)',
  'German 10-y Bond Auction': 'Mercredi – 11h30',
  'German 30-y Bond Auction': 'Variable',
  'German Bank Holiday': 'Variable',
  'German Buba Monthly Report': '15e – 12h00',
  'German Buba President Nagel Speaks': 'Variable',
  'German Factory Orders m/m': '6e – 08h00',
  'German Federal Elections': 'Sept. 2025 – non planifié',
  'German Final CPI m/m': '12e – 14h00',
  'German Final GDP q/q': '45e jour – 08h00',
  'German Final Manufacturing PMI': '1er jour ouvré – 09h30',
  'German Final Services PMI': '4e jour ouvré – 09h30',
  'German Flash Manufacturing PMI': '23e – 09h30',
  'German Flash Services PMI': '23e – 09h30',
  'German GfK Consumer Climate': '27e – 08h00',
  'German Import Prices m/m': '30e – 08h00',
  'German Industrial Production m/m': '7e – 08h00',
  'German PPI m/m': '20e – 08h00',
  'German Prelim CPI m/m': '30e – 14h00',
  'German Prelim GDP q/q': '30e – 08h00',
  'German Retail Sales m/m': '30e – 08h00',
  'German Trade Balance': '8e – 08h00',
  'German Unemployment Change': '1er jour ouvré – 09h55',
  'German WPI m/m': '15e – 08h00',
  'German ZEW Economic Sentiment': '2e mardi – 11h00',
  'German ifo Business Climate': '25e – 10h00',
  'Sentix Investor Confidence': 'Variable',
  'ZEW Economic Sentiment': '2e mardi – 11h00',
  'Autumn Forecast Statement': 'Novembre – variable',
  'Average Earnings Index 3m/y': '2e mardi – 08h00',
  'BOE Credit Conditions Survey': 'Trimestriel – 12h00',
  'BOE Financial Stability Report': 'Juin & Déc. – 12h00',
  'BOE Gov Bailey Speaks': 'Variable',
  'BOE Inflation Letter': 'Variable',
  'BOE Monetary Policy Report': 'Trimestriel – 12h00',
  'BOE Quarterly Bulletin': 'Trimestriel – 12h00',
  'BRC Retail Sales Monitor y/y': '1er mardi – 01h01',
  'BRC Shop Price Index y/y': '1er mercredi – 01h01',
  'CBI Industrial Order Expectations': '25e – 12h00',
  'CBI Realized Sales': '25e – 12h00',
  'Claimant Count Change': '2e mardi – 08h00',
  'Construction Output m/m': '10e – 08h00',
  'Construction Work Done q/q': '10e – 08h00',
  'FPC Meeting Minutes': 'Variable',
  'FPC Statement': 'Variable',
  'GfK Consumer Confidence': 'Dernier vendredi – 01h01',
  'Halifax HPI m/m': '7e – 09h00',
  'Housing Equity Withdrawal q/q': 'Trimestriel – 08h00',
  'IPPI m/m': '3e mercredi – 08h00',
  'Index of Services 3m/3m': '10e – 08h00',
  'MPC Member Breeden Speaks': 'Variable',
  'MPC Member Broadbent Speaks': 'Variable',
  'MPC Member Dhingra Speaks': 'Variable',
  'MPC Member Greene Speaks': 'Variable',
  'MPC Member Haskel Speaks': 'Variable',
  'MPC Member Lombardelli Speaks': 'Variable',
  'MPC Member Mann Speaks': 'Variable',
  'MPC Member Pill Speaks': 'Variable',
  'MPC Member Ramsden Speaks': 'Variable',
  'MPC Member Taylor Speaks': 'Variable',
  'MPC Official Bank Rate Votes': 'MPC – 13h00',
  'NIESR GDP Estimate': 'Variable',
  'Nationwide HPI m/m': '30e – 08h00',
  'Net Lending to Individuals m/m': '30e – 10h30',
  'Official Bank Rate': 'MPC – 13h00',
  'Overseas Trade Index q/q': 'Trimestriel – 08h00',
  'Parliamentary Elections': 'Variable – non planifié',
  'RICS House Price Balance': '12e – 01h01',
  'RMPI m/m': '1er mercredi – 01h01',
  'RPI y/y': '3e mercredi – 08h00',
  'RatingDog Manufacturing PMI': '1er jour ouvré – 00h00',
  'RatingDog Services PMI': '5e jour ouvré – 00h00',
  'Rightmove HPI m/m': '15e – 01h01',
  'Westpac Consumer Sentiment': 'Variable',
  'BOJ Core CPI y/y': 'Trimestriel – 01h30',
  'BOJ Gov Ueda Speaks': 'Variable',
  'BOJ Outlook Report': 'Trimestriel – 03h00',
  'BOJ Policy Rate': 'BOJ – 03h00-05h00',
  'BOJ Press Conference': 'BOJ – 06h30',
  'BOJ Summary of Opinions': '8 jours après – 01h50',
  'Bank Lending y/y': '8e – 01h50',
  'Caixin Manufacturing PMI': '1er jour ouvré – 02h45',
  'Caixin Services PMI': '5e jour ouvré – 02h45',
  'Cash Rate': 'BOJ – 03h00-05h00',
  'Core Machinery Orders m/m': '15e – 01h50',
  'Current Account': '8e – 01h50',
  'Economy Watchers Sentiment': '8e – 07h00',
  'Fixed Asset Investment ytd/y': '15e – 01h50',
  'Foreign Currency Reserves': '7e – 01h50',
  'GDP q/y': 'Trimestriel – 01h50',
  'Manufacturing Production m/m': '30e – 01h50',
  'National Core CPI y/y': '20e – 01h30',
  'New Loans': '8e – 01h50',
  'Prelim Machine Tool Orders y/y': '10e – 08h00',
  'Private Loans y/y': '8e – 01h50',
  'Tankan Manufacturing Index': '1er avril, juillet, oct., janv. – 01h50',
  'Tankan Non-Manufacturing Index': '1er avril, juillet, oct., janv. – 01h50',
  'Tertiary Industry Activity m/m': '15e – 05h30',
  'Tokyo Core CPI y/y': 'Dernier vendredi – 01h30',
  'Upper House Elections': 'Variable',
  'ANZ Business Confidence': '30e – 03h30',
  'ANZ Commodity Prices m/m': '1er jour ouvré – 04h00',
  'ANZ Job Advertisements m/m': '1er lundi – 03h30',
  'Average Cash Earnings y/y': 'Variable',
  'Building Approvals m/m': '1er jour ouvré – 03h30',
  'Building Consents m/m': '1er jour ouvré – 03h30',
  'NAB Business Confidence': '2e mardi – 03h30',
  'NAB Quarterly Business Confidence': 'Trimestriel – 03h30',
  'Private Capital Expenditure q/q': 'Trimestriel',
  'RBA Annual Report': 'Septembre – 03h30',
  'RBA Assist Gov Hunter Speaks': 'Variable',
  'RBA Assist Gov Jones Speaks': 'Variable',
  'RBA Assist Gov Kent Speaks': 'Variable',
  'RBA Bulletin': 'Trimestriel – 03h30',
  'RBA Deputy Gov Hauser Speaks': 'Variable',
  'RBA Financial Stability Review': 'Avril & Oct. – 03h30',
  'RBA Gov Bullock Speaks': 'Variable',
  'RBA Monetary Policy Statement': 'Trimestriel – 03h30',
  'RBA Press Conference': 'Trimestriel – 04h30',
  'RBA Rate Statement': 'Variable – 05h30',
  'Wage Price Index q/q': 'Trimestriel – 03h30',
  'BusinessNZ Manufacturing Index': '10e – 22h30 (veille)',
  'BusinessNZ Services Index': '5e – 22h30 (veille)',
  'Consumer Credit m/m': '30e – 03h00',
  'NHPI m/m': 'Mensuel – 03h00',
  'NZIER Business Confidence': 'Trimestriel – 03h00',
  'Official Cash Rate': 'RBNZ – 02h00',
  'Private Sector Credit m/m': '30e – 03h00',
  'RBNZ Financial Stability Report': 'Mai & Nov. – 22h00 (veille)',
  'RBNZ Gov Hawkesby Speaks': 'Variable',
  'RBNZ Gov Orr Speaks': 'Variable',
  'RBNZ Monetary Policy Statement': 'Trimestriel – 02h00',
  'RBNZ Press Conference': 'Trimestriel – 03h00',
  'RBNZ Rate Statement': 'RBNZ – 02h00',
  'Visitor Arrivals m/m': '20e – 22h45 (veille)',
  'BOC Business Outlook Survey': 'Trimestriel – 15h30',
  'BOC Financial System Review': 'Mai & Nov. – 15h45',
  'BOC Gov Macklem Speaks': 'Variable',
  'BOC Monetary Policy Report': 'Trimestriel – 15h45',
  'BOC Press Conference': 'Trimestriel – 16h15',
  'BOC Rate Statement': 'BOC – 15h45',
  'BOC Summary of Deliberations': '2 semaines après – 15h45',
  'Capital Spending q/y': 'Trimestriel – 14h30',
  'Company Operating Profits q/q': 'Trimestriel – 14h30',
  'Consumer Inflation Expectations': 'Trimestriel – 14h30',
  'Corporate Profits q/q': 'Trimestriel – 14h30',
  'Credit Card Spending y/y': 'Mensuel – 14h30',
  'Employment Change': '1er vendredi – 14h30',
  'GDP m/m': '30e – 14h30',
  'Gov Council Member Gravelle Speaks': 'Variable',
  'Gov Council Member Kozicki Speaks': 'Variable',
  'Gov Council Member Mendes Speaks': 'Variable',
  'Gov Council Member Rogers Speaks': 'Variable',
  'Gov Council Member Vincent Speaks': 'Variable',
  'Ivey PMI': '5e jour ouvré – 16h00',
  'Manufacturing Sales m/m': '15e – 14h30',
  'Manufacturing Sales q/q': 'Trimestriel – 14h30',
  'Credit Suisse Economic Expectations': 'Mensuel – variable',
  'Daylight Saving Time Shift': 'Mars & Oct. – non planifié',
  'Gov Board Member Martin Speaks': 'Variable',
  'Gov Board Member Schlegel Speaks': 'Variable',
  'Gov Board Member Tschudin Speaks': 'Variable',
  'KOF Economic Barometer': '30e – 09h00',
  'Overnight Rate': 'SNB – 09h30',
  'SECO Consumer Climate': 'Trimestriel – 08h00',
  'SECO Economic Forecasts': 'Trimestriel – 08h00',
  'SNB Chairman Jordan Speaks': 'Variable',
  'SNB Chairman Schlegel Speaks': 'Variable',
  'SNB Financial Stability Report': 'Juin – 09h30',
  'SNB Monetary Policy Assessment': 'Trimestriel – 09h30',
  'SNB Policy Rate': 'SNB – 09h30',
  'SNB Press Conference': 'SNB – 10h00',
  'SNB Quarterly Bulletin': 'Trimestriel – 09h30',
  'UBS Economic Expectations': 'Mensuel – variable',
  'French 10-y Bond Auction': '1er jeudi – 10h50',
  'French Bank Holiday': 'Variable',
  'French Consumer Spending m/m': '30e – 07h30',
  'French Final CPI m/m': '15e – 08h45',
  'French Final Manufacturing PMI': '1er jour ouvré – 09h50',
  'French Final Private Payrolls q/q': 'Trimestriel – 07h30',
  'French Final Services PMI': '5e jour ouvré – 09h50',
  'French Flash GDP q/q': '30e – 07h30',
  'French Flash Manufacturing PMI': '23e – 09h15',
  'French Flash Services PMI': '23e – 09h15',
  'French Gov Budget Balance': 'Trimestriel – 08h45',
  'French Industrial Production m/m': '10e – 08h45',
  'French Parliamentary Elections': 'Juin/Juillet – non planifié',
  'French Prelim CPI m/m': '30e – 08h45',
  'French Prelim GDP q/q': '45e jour – 07h30',
  'French Prelim Private Payrolls q/q': 'Trimestriel – 07h30',
  'French Trade Balance': '7e – 08h45',
  'Inflation Expectations q/q': 'Trimestriel – 08h45',
  'Lower House Elections': 'Juin/Juillet – non planifié',
  'Public Sector Net Borrowing': 'Mensuel – 09h00',
  'Spanish 10-y Bond Auction': 'Jeudi – 10h30',
  'Spanish Flash CPI y/y': '30e – 09h00',
  'Spanish Flash GDP q/q': '30e – 09h00',
  'Spanish Manufacturing PMI': '1er jour ouvré – 09h15',
  'Spanish Services PMI': '5e jour ouvré – 09h15',
  'Spanish Unemployment Change': '1er jour ouvré – 09h00',
  'Spanish Unemployment Rate': 'Trimestriel – 09h00',
  'Italian 10-y Bond Auction': 'Variable – 11h00',
  'Italian Bank Holiday': 'Variable',
  'Italian Industrial Production m/m': '10e – 10h00',
  'Italian Manufacturing PMI': '1er jour ouvré – 09h45',
  'Italian Monthly Unemployment Rate': '30e – 10h00',
  'Italian Prelim CPI m/m': '30e – 11h00',
  'Italian Prelim GDP q/q': '30e – 10h00',
  'Italian Quarterly Unemployment Rate': 'Trimestriel – 10h00',
  'Italian Retail Sales m/m': '7e – 10h00',
  'Italian Services PMI': '5e jour ouvré – 09h45',
  'Italian Trade Balance': '15e – 10h00',
  'Belgian NBB Business Climate': '20e – 15h00',
  'Commodity Prices y/y': 'Mensuel – 03h00',
  'Foreign Direct Investment ytd/y': '20e – 09h00',
  'M2 Money Stock y/y': '15e – 09h00',
  'NBS Press Conference': 'Trimestriel – 03h00',
  '10-y Bond Auction': 'Variable',
  '30-y Bond Auction': 'Variable',
  'BRICS Summit': 'Variable',
  'Common CPI y/y': 'Variable',
  'FPI m/m': 'Variable',
  'G20 Meetings': 'Variable',
  'G7 Meetings': 'Variable',
  'GDT Price Index': 'Variable',
  'IMF Meetings': 'Variable',
  'Loan Officer Survey': 'Variable',
  'M2 Money Supply y/y': 'Variable',
  'M3 Money Supply y/y': 'Variable',
  'M4 Money Supply m/m': 'Variable',
  'Mid-Year Economic and Fiscal Outlook': 'Variable',
  'OPEC Meetings': 'Variable',
  'OPEC-JMMC Meetings': 'Variable',
  'S&P/CS Composite-20 HPI y/y': 'Variable',
  'SPPI y/y': 'Variable',
};

export function getEventSchedule(eventName: string): string {
  return eventSchedules[eventName] || 'Variable';
}
